# Generated by Django 5.2.13 on 2026-05-03 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_url', models.URLField(max_length=1000, unique=True, verbose_name='URL Công việc')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tiêu đề công việc')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên công ty')),
                ('company_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link công ty')),
                ('contract_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại hợp đồng')),
                ('deadline', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hạn nộp hồ sơ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả công việc')),
                ('experience_level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kinh nghiệm')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa điểm')),
                ('posted_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Thời gian đăng')),
                ('salary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mức lương')),
                ('sector', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ngành nghề')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Từ khóa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên Domain (vd: topcv, vnworks)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True, verbose_name='URL Công việc')),
                ('domain', models.CharField(max_length=100, verbose_name='Domain')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('tried_count', models.IntegerField(default=0, verbose_name='Số lần thử')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='job_links', to='app_dashboard.keyword', verbose_name='Từ khóa')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'domain'], name='app_dashboa_status_f38606_idx')],
            },
        ),
    ]
