# Generated by Django 5.2.13 on 2026-05-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetdomain',
            name='extract_runs_per_day',
            field=models.PositiveIntegerField(default=24, help_text='So lan boc tach chi tiet job trong 1 ngay cho domain nay.', verbose_name='So lan chay Extractor/ngay'),
        ),
        migrations.AddField(
            model_name='targetdomain',
            name='harvest_runs_per_day',
            field=models.PositiveIntegerField(default=1, help_text='So lan thu thap link moi trong 1 ngay cho domain nay.', verbose_name='So lan chay Harvester/ngay'),
        ),
        migrations.AddField(
            model_name='targetdomain',
            name='job_read_time_seconds',
            field=models.PositiveIntegerField(default=3, help_text='Thoi gian cho/gia lap doc trang job detail truoc khi extract.', verbose_name='Thoi gian doc job (giay)'),
        ),
    ]
