# Generated by Django 5.2.13 on 2026-05-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0002_targetdomain_extract_runs_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetdomain',
            name='extract_batch_size',
            field=models.PositiveIntegerField(default=3, help_text='So link PENDING toi da duoc lock va xu ly trong mot lan chay extractor.', verbose_name='Batch size Extractor'),
        ),
        migrations.AddField(
            model_name='targetdomain',
            name='is_extract_enabled',
            field=models.BooleanField(default=True, help_text='Cho phep domain nay boc tach chi tiet job.', verbose_name='Bat Extractor'),
        ),
        migrations.AddField(
            model_name='targetdomain',
            name='is_harvest_enabled',
            field=models.BooleanField(default=True, help_text='Cho phep domain nay thu thap link moi.', verbose_name='Bat Harvester'),
        ),
        migrations.AddField(
            model_name='targetdomain',
            name='max_pages_per_keyword',
            field=models.PositiveIntegerField(default=5, help_text='Gioi han so trang danh sach viec lam duoc crawl cho moi keyword.', verbose_name='So trang toi da/keyword'),
        ),
        migrations.AddField(
            model_name='targetdomain',
            name='request_delay_max_seconds',
            field=models.PositiveIntegerField(default=3, help_text='Thoi gian cho ngau nhien toi da sau khi trang load.', verbose_name='Delay lon nhat/request (giay)'),
        ),
        migrations.AddField(
            model_name='targetdomain',
            name='request_delay_min_seconds',
            field=models.PositiveIntegerField(default=1, help_text='Thoi gian cho ngau nhien toi thieu sau khi trang load.', verbose_name='Delay nho nhat/request (giay)'),
        ),
    ]
