# Generated by Django 5.2.13 on 2026-05-14 16:06

from django.db import migrations, models


def create_linkedin_domain(apps, schema_editor):
    TargetDomain = apps.get_model('app_dashboard', 'TargetDomain')
    domain, created = TargetDomain.objects.get_or_create(
        name='linkedin',
        defaults={
            'is_active': False,
            'is_harvest_enabled': True,
            'is_extract_enabled': False,
            'harvest_runs_per_day': 1,
            'extract_runs_per_day': 0,
            'job_read_time_seconds': 3,
            'max_pages_per_keyword': 5,
            'max_jobs_per_keyword': 100,
            'search_locations': ['Vietnam'],
            'extract_batch_size': 3,
            'request_delay_min_seconds': 1,
            'request_delay_max_seconds': 3,
        },
    )
    if not created:
        updates = {}
        if not domain.search_locations:
            updates['search_locations'] = ['Vietnam']
        if domain.is_extract_enabled:
            updates['is_extract_enabled'] = False
        if updates:
            TargetDomain.objects.filter(pk=domain.pk).update(**updates)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0003_targetdomain_extract_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetdomain',
            name='max_jobs_per_keyword',
            field=models.PositiveIntegerField(default=100, help_text='Gioi han tong so job URL duoc luu cho moi keyword trong mot vong harvest.', verbose_name='So job toi da/keyword'),
        ),
        migrations.AddField(
            model_name='targetdomain',
            name='search_locations',
            field=models.JSONField(blank=True, default=list, help_text='Danh sach location cho search, vi du: ["Vietnam", "Ho Chi Minh City, Vietnam"].', verbose_name='Dia diem tim kiem'),
        ),
        migrations.RunPython(create_linkedin_domain, noop_reverse),
    ]
