# Generated by Codex on 2026-05-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0004_targetdomain_max_jobs_per_keyword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên proxy')),
                (
                    'proxy_url',
                    models.URLField(
                        help_text='Định dạng: http://user:pass@host:port hoặc https://user:pass@host:port.',
                        max_length=1000,
                        verbose_name='Proxy URL',
                    ),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                (
                    'priority',
                    models.PositiveIntegerField(
                        default=100,
                        help_text='Số nhỏ hơn được ưu tiên dùng trước.',
                        verbose_name='Độ ưu tiên',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'domain',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text='Để trống nếu proxy này dùng chung cho mọi domain.',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='proxy_configs',
                        to='app_dashboard.targetdomain',
                        verbose_name='Domain',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Proxy',
                'verbose_name_plural': 'Proxies',
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['is_active', 'domain', 'priority'], name='app_dashboa_is_acti_98e782_idx')],
            },
        ),
    ]
