# Generated by Codex on 2026-05-31

from django.db import migrations, models


def copy_keyword_names(apps, schema_editor):
    JobLink = apps.get_model('app_dashboard', 'JobLink')

    for link in JobLink.objects.select_related('keyword').iterator():
        keyword = getattr(link, 'keyword', None)
        link.keyword_text = keyword.name if keyword else ''
        link.save(update_fields=['keyword_text'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0005_proxyconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblink',
            name='keyword_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Từ khóa'),
        ),
        migrations.RunPython(copy_keyword_names, noop_reverse),
        migrations.RemoveField(
            model_name='joblink',
            name='keyword',
        ),
        migrations.RenameField(
            model_name='joblink',
            old_name='keyword_text',
            new_name='keyword',
        ),
        migrations.AlterField(
            model_name='joblink',
            name='keyword',
            field=models.CharField(max_length=255, verbose_name='Từ khóa'),
        ),
    ]
