# Generated by Codex on 2026-06-07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0006_joblink_keyword_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, verbose_name='Domain')),
                (
                    'mode',
                    models.CharField(
                        choices=[('HARVEST', 'Harvest'), ('EXTRACT', 'Extract')],
                        max_length=20,
                        verbose_name='Loáº¡i worker',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')],
                        default='STARTED',
                        max_length=20,
                        verbose_name='Tráº¡ng thÃ¡i',
                    ),
                ),
                ('run_date', models.DateField(db_index=True, verbose_name='NgÃ y cháº¡y')),
                ('run_number', models.PositiveIntegerField(verbose_name='Láº§n cháº¡y trong ngÃ y')),
                ('configured_runs', models.PositiveIntegerField(verbose_name='Tá»•ng sá»‘ láº§n cáº¥u hÃ¬nh/ngÃ y')),
                (
                    'started_at',
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name='Báº¯t Ä‘áº§u',
                    ),
                ),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Káº¿t thÃºc')),
                ('items_count', models.PositiveIntegerField(default=0, verbose_name='Sá»‘ item xá»­ lÃ½')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Lá»—i')),
            ],
            options={
                'verbose_name': 'Lá»‹ch sá»­ cháº¡y domain',
                'verbose_name_plural': 'Lá»‹ch sá»­ cháº¡y domain',
                'ordering': ['-started_at', '-id'],
                'indexes': [
                    models.Index(
                        fields=['domain', 'mode', 'run_date', 'status'],
                        name='app_dashboa_domain_8ad560_idx',
                    ),
                ],
            },
        ),
    ]
