# Generated by Codex on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0007_domainrunlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetdomain',
            name='is_proxy_enabled',
            field=models.BooleanField(
                default=True,
                help_text='Use configured proxies for this domain when running harvesters and extractors.',
                verbose_name='Enable proxy',
            ),
        ),
    ]
